/*
 * Jobs API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.job.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.smartrecruiters.api.job.model.HeadcountPatchRequestSalaryRange;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * HeadcountPatchRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-01T16:01:57.232855+01:00[Europe/Rome]")
public class HeadcountPatchRequest {
  public static final String SERIALIZED_NAME_SALARY_RANGE = "salaryRange";
  @SerializedName(SERIALIZED_NAME_SALARY_RANGE)
  private HeadcountPatchRequestSalaryRange salaryRange;


  public HeadcountPatchRequest salaryRange(HeadcountPatchRequestSalaryRange salaryRange) {
    
    this.salaryRange = salaryRange;
    return this;
  }

   /**
   * Get salaryRange
   * @return salaryRange
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HeadcountPatchRequestSalaryRange getSalaryRange() {
    return salaryRange;
  }



  public void setSalaryRange(HeadcountPatchRequestSalaryRange salaryRange) {
    this.salaryRange = salaryRange;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HeadcountPatchRequest headcountPatchRequest = (HeadcountPatchRequest) o;
    return Objects.equals(this.salaryRange, headcountPatchRequest.salaryRange);
  }

  @Override
  public int hashCode() {
    return Objects.hash(salaryRange);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HeadcountPatchRequest {\n");
    sb.append("    salaryRange: ").append(toIndentedString(salaryRange)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

