/*
 * Jobs API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.job.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets HiringTeamMemberRole
 */
@JsonAdapter(HiringTeamMemberRole.Adapter.class)
public enum HiringTeamMemberRole {
  
  HIRING_MANAGER("HIRING_MANAGER"),
  
  INTERVIEW_TEAM("INTERVIEW_TEAM"),
  
  RECRUITER("RECRUITER"),
  
  EXECUTIVE("EXECUTIVE"),
  
  COORDINATOR("COORDINATOR");

  private String value;

  HiringTeamMemberRole(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static HiringTeamMemberRole fromValue(String value) {
    for (HiringTeamMemberRole b : HiringTeamMemberRole.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<HiringTeamMemberRole> {
    @Override
    public void write(final JsonWriter jsonWriter, final HiringTeamMemberRole enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public HiringTeamMemberRole read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return HiringTeamMemberRole.fromValue(value);
    }
  }
}

