/*
 * Jobs API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.job.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * JobAdUnpublishScheduled
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-01T16:01:57.232855+01:00[Europe/Rome]")
public class JobAdUnpublishScheduled {
  /**
   * Gets or Sets unpostingStatus
   */
  @JsonAdapter(UnpostingStatusEnum.Adapter.class)
  public enum UnpostingStatusEnum {
    PENDING("PENDING");

    private String value;

    UnpostingStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static UnpostingStatusEnum fromValue(String value) {
      for (UnpostingStatusEnum b : UnpostingStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<UnpostingStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final UnpostingStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public UnpostingStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return UnpostingStatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_UNPOSTING_STATUS = "unpostingStatus";
  @SerializedName(SERIALIZED_NAME_UNPOSTING_STATUS)
  private UnpostingStatusEnum unpostingStatus;


  public JobAdUnpublishScheduled unpostingStatus(UnpostingStatusEnum unpostingStatus) {
    
    this.unpostingStatus = unpostingStatus;
    return this;
  }

   /**
   * Get unpostingStatus
   * @return unpostingStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UnpostingStatusEnum getUnpostingStatus() {
    return unpostingStatus;
  }



  public void setUnpostingStatus(UnpostingStatusEnum unpostingStatus) {
    this.unpostingStatus = unpostingStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobAdUnpublishScheduled jobAdUnpublishScheduled = (JobAdUnpublishScheduled) o;
    return Objects.equals(this.unpostingStatus, jobAdUnpublishScheduled.unpostingStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unpostingStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobAdUnpublishScheduled {\n");
    sb.append("    unpostingStatus: ").append(toIndentedString(unpostingStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

