/*
 * Jobs API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.job.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * JobAdPublicationScheduled
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-01T16:01:57.232855+01:00[Europe/Rome]")
public class JobAdPublicationScheduled {
  /**
   * Gets or Sets postingStatus
   */
  @JsonAdapter(PostingStatusEnum.Adapter.class)
  public enum PostingStatusEnum {
    PENDING("PENDING");

    private String value;

    PostingStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PostingStatusEnum fromValue(String value) {
      for (PostingStatusEnum b : PostingStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PostingStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PostingStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PostingStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PostingStatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_POSTING_STATUS = "postingStatus";
  @SerializedName(SERIALIZED_NAME_POSTING_STATUS)
  private PostingStatusEnum postingStatus;


  public JobAdPublicationScheduled postingStatus(PostingStatusEnum postingStatus) {
    
    this.postingStatus = postingStatus;
    return this;
  }

   /**
   * Get postingStatus
   * @return postingStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PostingStatusEnum getPostingStatus() {
    return postingStatus;
  }



  public void setPostingStatus(PostingStatusEnum postingStatus) {
    this.postingStatus = postingStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobAdPublicationScheduled jobAdPublicationScheduled = (JobAdPublicationScheduled) o;
    return Objects.equals(this.postingStatus, jobAdPublicationScheduled.postingStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postingStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobAdPublicationScheduled {\n");
    sb.append("    postingStatus: ").append(toIndentedString(postingStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

