/*
 * Jobs API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.job.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.smartrecruiters.api.job.model.Compensation;
import com.smartrecruiters.api.job.model.Department;
import com.smartrecruiters.api.job.model.Job;
import com.smartrecruiters.api.job.model.JobAdInput;
import com.smartrecruiters.api.job.model.JobDetailsAllOf;
import com.smartrecruiters.api.job.model.JobDetailsAllOfActions;
import com.smartrecruiters.api.job.model.JobProperty;
import com.smartrecruiters.api.job.model.JobStatus;
import com.smartrecruiters.api.job.model.Location;
import com.smartrecruiters.api.job.model.PostingStatus;
import com.smartrecruiters.api.job.model.Property;
import com.smartrecruiters.api.job.model.UserIdentity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * JobDetails
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-01T16:01:57.232855+01:00[Europe/Rome]")
public class JobDetails {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_REF_NUMBER = "refNumber";
  @SerializedName(SERIALIZED_NAME_REF_NUMBER)
  private String refNumber;

  public static final String SERIALIZED_NAME_CREATED_ON = "createdOn";
  @SerializedName(SERIALIZED_NAME_CREATED_ON)
  private OffsetDateTime createdOn;

  public static final String SERIALIZED_NAME_UPDATED_ON = "updatedOn";
  @SerializedName(SERIALIZED_NAME_UPDATED_ON)
  private OffsetDateTime updatedOn;

  public static final String SERIALIZED_NAME_LAST_ACTIVITY_ON = "lastActivityOn";
  @SerializedName(SERIALIZED_NAME_LAST_ACTIVITY_ON)
  private OffsetDateTime lastActivityOn;

  public static final String SERIALIZED_NAME_DEPARTMENT = "department";
  @SerializedName(SERIALIZED_NAME_DEPARTMENT)
  private Department department;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private Location location;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private JobStatus status;

  public static final String SERIALIZED_NAME_POSTING_STATUS = "postingStatus";
  @SerializedName(SERIALIZED_NAME_POSTING_STATUS)
  private PostingStatus postingStatus;

  public static final String SERIALIZED_NAME_TARGET_HIRING_DATE = "targetHiringDate";
  @SerializedName(SERIALIZED_NAME_TARGET_HIRING_DATE)
  private OffsetDateTime targetHiringDate;

  public static final String SERIALIZED_NAME_INDUSTRY = "industry";
  @SerializedName(SERIALIZED_NAME_INDUSTRY)
  private Property industry;

  public static final String SERIALIZED_NAME_FUNCTION = "function";
  @SerializedName(SERIALIZED_NAME_FUNCTION)
  private Property function;

  public static final String SERIALIZED_NAME_TYPE_OF_EMPLOYMENT = "typeOfEmployment";
  @SerializedName(SERIALIZED_NAME_TYPE_OF_EMPLOYMENT)
  private Property typeOfEmployment;

  public static final String SERIALIZED_NAME_EXPERIENCE_LEVEL = "experienceLevel";
  @SerializedName(SERIALIZED_NAME_EXPERIENCE_LEVEL)
  private Property experienceLevel;

  public static final String SERIALIZED_NAME_EEO_CATEGORY = "eeoCategory";
  @SerializedName(SERIALIZED_NAME_EEO_CATEGORY)
  private Property eeoCategory;

  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  private Boolean template;

  public static final String SERIALIZED_NAME_CREATOR = "creator";
  @SerializedName(SERIALIZED_NAME_CREATOR)
  private UserIdentity creator;

  public static final String SERIALIZED_NAME_COMPENSATION = "compensation";
  @SerializedName(SERIALIZED_NAME_COMPENSATION)
  private Compensation compensation;

  public static final String SERIALIZED_NAME_JOB_AD = "jobAd";
  @SerializedName(SERIALIZED_NAME_JOB_AD)
  private JobAdInput jobAd;

  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  private List<JobProperty> properties = null;

  public static final String SERIALIZED_NAME_ACTIONS = "actions";
  @SerializedName(SERIALIZED_NAME_ACTIONS)
  private JobDetailsAllOfActions actions;


  public JobDetails id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }



  public void setId(String id) {
    this.id = id;
  }


  public JobDetails title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTitle() {
    return title;
  }



  public void setTitle(String title) {
    this.title = title;
  }


  public JobDetails refNumber(String refNumber) {
    
    this.refNumber = refNumber;
    return this;
  }

   /**
   * Get refNumber
   * @return refNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRefNumber() {
    return refNumber;
  }



  public void setRefNumber(String refNumber) {
    this.refNumber = refNumber;
  }


  public JobDetails createdOn(OffsetDateTime createdOn) {
    
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }



  public void setCreatedOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
  }


  public JobDetails updatedOn(OffsetDateTime updatedOn) {
    
    this.updatedOn = updatedOn;
    return this;
  }

   /**
   * Job modification date
   * @return updatedOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Job modification date")

  public OffsetDateTime getUpdatedOn() {
    return updatedOn;
  }



  public void setUpdatedOn(OffsetDateTime updatedOn) {
    this.updatedOn = updatedOn;
  }


  public JobDetails lastActivityOn(OffsetDateTime lastActivityOn) {
    
    this.lastActivityOn = lastActivityOn;
    return this;
  }

   /**
   * Indicates last activity associated with a job
   * @return lastActivityOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates last activity associated with a job")

  public OffsetDateTime getLastActivityOn() {
    return lastActivityOn;
  }



  public void setLastActivityOn(OffsetDateTime lastActivityOn) {
    this.lastActivityOn = lastActivityOn;
  }


  public JobDetails department(Department department) {
    
    this.department = department;
    return this;
  }

   /**
   * Get department
   * @return department
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Department getDepartment() {
    return department;
  }



  public void setDepartment(Department department) {
    this.department = department;
  }


  public JobDetails location(Location location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Location getLocation() {
    return location;
  }



  public void setLocation(Location location) {
    this.location = location;
  }


  public JobDetails status(JobStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JobStatus getStatus() {
    return status;
  }



  public void setStatus(JobStatus status) {
    this.status = status;
  }


  public JobDetails postingStatus(PostingStatus postingStatus) {
    
    this.postingStatus = postingStatus;
    return this;
  }

   /**
   * Get postingStatus
   * @return postingStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PostingStatus getPostingStatus() {
    return postingStatus;
  }



  public void setPostingStatus(PostingStatus postingStatus) {
    this.postingStatus = postingStatus;
  }


  public JobDetails targetHiringDate(OffsetDateTime targetHiringDate) {
    
    this.targetHiringDate = targetHiringDate;
    return this;
  }

   /**
   * Get targetHiringDate
   * @return targetHiringDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getTargetHiringDate() {
    return targetHiringDate;
  }



  public void setTargetHiringDate(OffsetDateTime targetHiringDate) {
    this.targetHiringDate = targetHiringDate;
  }


  public JobDetails industry(Property industry) {
    
    this.industry = industry;
    return this;
  }

   /**
   * Get industry
   * @return industry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Property getIndustry() {
    return industry;
  }



  public void setIndustry(Property industry) {
    this.industry = industry;
  }


  public JobDetails function(Property function) {
    
    this.function = function;
    return this;
  }

   /**
   * Get function
   * @return function
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Property getFunction() {
    return function;
  }



  public void setFunction(Property function) {
    this.function = function;
  }


  public JobDetails typeOfEmployment(Property typeOfEmployment) {
    
    this.typeOfEmployment = typeOfEmployment;
    return this;
  }

   /**
   * Get typeOfEmployment
   * @return typeOfEmployment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Property getTypeOfEmployment() {
    return typeOfEmployment;
  }



  public void setTypeOfEmployment(Property typeOfEmployment) {
    this.typeOfEmployment = typeOfEmployment;
  }


  public JobDetails experienceLevel(Property experienceLevel) {
    
    this.experienceLevel = experienceLevel;
    return this;
  }

   /**
   * Get experienceLevel
   * @return experienceLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Property getExperienceLevel() {
    return experienceLevel;
  }



  public void setExperienceLevel(Property experienceLevel) {
    this.experienceLevel = experienceLevel;
  }


  public JobDetails eeoCategory(Property eeoCategory) {
    
    this.eeoCategory = eeoCategory;
    return this;
  }

   /**
   * Get eeoCategory
   * @return eeoCategory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Property getEeoCategory() {
    return eeoCategory;
  }



  public void setEeoCategory(Property eeoCategory) {
    this.eeoCategory = eeoCategory;
  }


  public JobDetails template(Boolean template) {
    
    this.template = template;
    return this;
  }

   /**
   * Get template
   * @return template
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getTemplate() {
    return template;
  }



  public void setTemplate(Boolean template) {
    this.template = template;
  }


  public JobDetails creator(UserIdentity creator) {
    
    this.creator = creator;
    return this;
  }

   /**
   * Get creator
   * @return creator
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UserIdentity getCreator() {
    return creator;
  }



  public void setCreator(UserIdentity creator) {
    this.creator = creator;
  }


  public JobDetails compensation(Compensation compensation) {
    
    this.compensation = compensation;
    return this;
  }

   /**
   * Get compensation
   * @return compensation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Compensation getCompensation() {
    return compensation;
  }



  public void setCompensation(Compensation compensation) {
    this.compensation = compensation;
  }


  public JobDetails jobAd(JobAdInput jobAd) {
    
    this.jobAd = jobAd;
    return this;
  }

   /**
   * Get jobAd
   * @return jobAd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JobAdInput getJobAd() {
    return jobAd;
  }



  public void setJobAd(JobAdInput jobAd) {
    this.jobAd = jobAd;
  }


  public JobDetails properties(List<JobProperty> properties) {
    
    this.properties = properties;
    return this;
  }

  public JobDetails addPropertiesItem(JobProperty propertiesItem) {
    if (this.properties == null) {
      this.properties = new ArrayList<JobProperty>();
    }
    this.properties.add(propertiesItem);
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<JobProperty> getProperties() {
    return properties;
  }



  public void setProperties(List<JobProperty> properties) {
    this.properties = properties;
  }


  public JobDetails actions(JobDetailsAllOfActions actions) {
    
    this.actions = actions;
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JobDetailsAllOfActions getActions() {
    return actions;
  }



  public void setActions(JobDetailsAllOfActions actions) {
    this.actions = actions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobDetails jobDetails = (JobDetails) o;
    return Objects.equals(this.id, jobDetails.id) &&
        Objects.equals(this.title, jobDetails.title) &&
        Objects.equals(this.refNumber, jobDetails.refNumber) &&
        Objects.equals(this.createdOn, jobDetails.createdOn) &&
        Objects.equals(this.updatedOn, jobDetails.updatedOn) &&
        Objects.equals(this.lastActivityOn, jobDetails.lastActivityOn) &&
        Objects.equals(this.department, jobDetails.department) &&
        Objects.equals(this.location, jobDetails.location) &&
        Objects.equals(this.status, jobDetails.status) &&
        Objects.equals(this.postingStatus, jobDetails.postingStatus) &&
        Objects.equals(this.targetHiringDate, jobDetails.targetHiringDate) &&
        Objects.equals(this.industry, jobDetails.industry) &&
        Objects.equals(this.function, jobDetails.function) &&
        Objects.equals(this.typeOfEmployment, jobDetails.typeOfEmployment) &&
        Objects.equals(this.experienceLevel, jobDetails.experienceLevel) &&
        Objects.equals(this.eeoCategory, jobDetails.eeoCategory) &&
        Objects.equals(this.template, jobDetails.template) &&
        Objects.equals(this.creator, jobDetails.creator) &&
        Objects.equals(this.compensation, jobDetails.compensation) &&
        Objects.equals(this.jobAd, jobDetails.jobAd) &&
        Objects.equals(this.properties, jobDetails.properties) &&
        Objects.equals(this.actions, jobDetails.actions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, refNumber, createdOn, updatedOn, lastActivityOn, department, location, status, postingStatus, targetHiringDate, industry, function, typeOfEmployment, experienceLevel, eeoCategory, template, creator, compensation, jobAd, properties, actions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobDetails {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    refNumber: ").append(toIndentedString(refNumber)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("    lastActivityOn: ").append(toIndentedString(lastActivityOn)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    postingStatus: ").append(toIndentedString(postingStatus)).append("\n");
    sb.append("    targetHiringDate: ").append(toIndentedString(targetHiringDate)).append("\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    sb.append("    typeOfEmployment: ").append(toIndentedString(typeOfEmployment)).append("\n");
    sb.append("    experienceLevel: ").append(toIndentedString(experienceLevel)).append("\n");
    sb.append("    eeoCategory: ").append(toIndentedString(eeoCategory)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    compensation: ").append(toIndentedString(compensation)).append("\n");
    sb.append("    jobAd: ").append(toIndentedString(jobAd)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

