/*
 * Jobs API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.job.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.smartrecruiters.api.job.model.Compensation;
import com.smartrecruiters.api.job.model.JobAdInput;
import com.smartrecruiters.api.job.model.JobDetailsAllOfActions;
import com.smartrecruiters.api.job.model.JobProperty;
import com.smartrecruiters.api.job.model.Property;
import com.smartrecruiters.api.job.model.UserIdentity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * JobDetailsAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-01T16:01:57.232855+01:00[Europe/Rome]")
public class JobDetailsAllOf {
  public static final String SERIALIZED_NAME_TARGET_HIRING_DATE = "targetHiringDate";
  @SerializedName(SERIALIZED_NAME_TARGET_HIRING_DATE)
  private OffsetDateTime targetHiringDate;

  public static final String SERIALIZED_NAME_INDUSTRY = "industry";
  @SerializedName(SERIALIZED_NAME_INDUSTRY)
  private Property industry;

  public static final String SERIALIZED_NAME_FUNCTION = "function";
  @SerializedName(SERIALIZED_NAME_FUNCTION)
  private Property function;

  public static final String SERIALIZED_NAME_TYPE_OF_EMPLOYMENT = "typeOfEmployment";
  @SerializedName(SERIALIZED_NAME_TYPE_OF_EMPLOYMENT)
  private Property typeOfEmployment;

  public static final String SERIALIZED_NAME_EXPERIENCE_LEVEL = "experienceLevel";
  @SerializedName(SERIALIZED_NAME_EXPERIENCE_LEVEL)
  private Property experienceLevel;

  public static final String SERIALIZED_NAME_EEO_CATEGORY = "eeoCategory";
  @SerializedName(SERIALIZED_NAME_EEO_CATEGORY)
  private Property eeoCategory;

  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  private Boolean template;

  public static final String SERIALIZED_NAME_CREATOR = "creator";
  @SerializedName(SERIALIZED_NAME_CREATOR)
  private UserIdentity creator;

  public static final String SERIALIZED_NAME_COMPENSATION = "compensation";
  @SerializedName(SERIALIZED_NAME_COMPENSATION)
  private Compensation compensation;

  public static final String SERIALIZED_NAME_JOB_AD = "jobAd";
  @SerializedName(SERIALIZED_NAME_JOB_AD)
  private JobAdInput jobAd;

  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  private List<JobProperty> properties = null;

  public static final String SERIALIZED_NAME_ACTIONS = "actions";
  @SerializedName(SERIALIZED_NAME_ACTIONS)
  private JobDetailsAllOfActions actions;


  public JobDetailsAllOf targetHiringDate(OffsetDateTime targetHiringDate) {
    
    this.targetHiringDate = targetHiringDate;
    return this;
  }

   /**
   * Get targetHiringDate
   * @return targetHiringDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getTargetHiringDate() {
    return targetHiringDate;
  }



  public void setTargetHiringDate(OffsetDateTime targetHiringDate) {
    this.targetHiringDate = targetHiringDate;
  }


  public JobDetailsAllOf industry(Property industry) {
    
    this.industry = industry;
    return this;
  }

   /**
   * Get industry
   * @return industry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Property getIndustry() {
    return industry;
  }



  public void setIndustry(Property industry) {
    this.industry = industry;
  }


  public JobDetailsAllOf function(Property function) {
    
    this.function = function;
    return this;
  }

   /**
   * Get function
   * @return function
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Property getFunction() {
    return function;
  }



  public void setFunction(Property function) {
    this.function = function;
  }


  public JobDetailsAllOf typeOfEmployment(Property typeOfEmployment) {
    
    this.typeOfEmployment = typeOfEmployment;
    return this;
  }

   /**
   * Get typeOfEmployment
   * @return typeOfEmployment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Property getTypeOfEmployment() {
    return typeOfEmployment;
  }



  public void setTypeOfEmployment(Property typeOfEmployment) {
    this.typeOfEmployment = typeOfEmployment;
  }


  public JobDetailsAllOf experienceLevel(Property experienceLevel) {
    
    this.experienceLevel = experienceLevel;
    return this;
  }

   /**
   * Get experienceLevel
   * @return experienceLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Property getExperienceLevel() {
    return experienceLevel;
  }



  public void setExperienceLevel(Property experienceLevel) {
    this.experienceLevel = experienceLevel;
  }


  public JobDetailsAllOf eeoCategory(Property eeoCategory) {
    
    this.eeoCategory = eeoCategory;
    return this;
  }

   /**
   * Get eeoCategory
   * @return eeoCategory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Property getEeoCategory() {
    return eeoCategory;
  }



  public void setEeoCategory(Property eeoCategory) {
    this.eeoCategory = eeoCategory;
  }


  public JobDetailsAllOf template(Boolean template) {
    
    this.template = template;
    return this;
  }

   /**
   * Get template
   * @return template
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getTemplate() {
    return template;
  }



  public void setTemplate(Boolean template) {
    this.template = template;
  }


  public JobDetailsAllOf creator(UserIdentity creator) {
    
    this.creator = creator;
    return this;
  }

   /**
   * Get creator
   * @return creator
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UserIdentity getCreator() {
    return creator;
  }



  public void setCreator(UserIdentity creator) {
    this.creator = creator;
  }


  public JobDetailsAllOf compensation(Compensation compensation) {
    
    this.compensation = compensation;
    return this;
  }

   /**
   * Get compensation
   * @return compensation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Compensation getCompensation() {
    return compensation;
  }



  public void setCompensation(Compensation compensation) {
    this.compensation = compensation;
  }


  public JobDetailsAllOf jobAd(JobAdInput jobAd) {
    
    this.jobAd = jobAd;
    return this;
  }

   /**
   * Get jobAd
   * @return jobAd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JobAdInput getJobAd() {
    return jobAd;
  }



  public void setJobAd(JobAdInput jobAd) {
    this.jobAd = jobAd;
  }


  public JobDetailsAllOf properties(List<JobProperty> properties) {
    
    this.properties = properties;
    return this;
  }

  public JobDetailsAllOf addPropertiesItem(JobProperty propertiesItem) {
    if (this.properties == null) {
      this.properties = new ArrayList<JobProperty>();
    }
    this.properties.add(propertiesItem);
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<JobProperty> getProperties() {
    return properties;
  }



  public void setProperties(List<JobProperty> properties) {
    this.properties = properties;
  }


  public JobDetailsAllOf actions(JobDetailsAllOfActions actions) {
    
    this.actions = actions;
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JobDetailsAllOfActions getActions() {
    return actions;
  }



  public void setActions(JobDetailsAllOfActions actions) {
    this.actions = actions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobDetailsAllOf jobDetailsAllOf = (JobDetailsAllOf) o;
    return Objects.equals(this.targetHiringDate, jobDetailsAllOf.targetHiringDate) &&
        Objects.equals(this.industry, jobDetailsAllOf.industry) &&
        Objects.equals(this.function, jobDetailsAllOf.function) &&
        Objects.equals(this.typeOfEmployment, jobDetailsAllOf.typeOfEmployment) &&
        Objects.equals(this.experienceLevel, jobDetailsAllOf.experienceLevel) &&
        Objects.equals(this.eeoCategory, jobDetailsAllOf.eeoCategory) &&
        Objects.equals(this.template, jobDetailsAllOf.template) &&
        Objects.equals(this.creator, jobDetailsAllOf.creator) &&
        Objects.equals(this.compensation, jobDetailsAllOf.compensation) &&
        Objects.equals(this.jobAd, jobDetailsAllOf.jobAd) &&
        Objects.equals(this.properties, jobDetailsAllOf.properties) &&
        Objects.equals(this.actions, jobDetailsAllOf.actions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(targetHiringDate, industry, function, typeOfEmployment, experienceLevel, eeoCategory, template, creator, compensation, jobAd, properties, actions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobDetailsAllOf {\n");
    sb.append("    targetHiringDate: ").append(toIndentedString(targetHiringDate)).append("\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    sb.append("    typeOfEmployment: ").append(toIndentedString(typeOfEmployment)).append("\n");
    sb.append("    experienceLevel: ").append(toIndentedString(experienceLevel)).append("\n");
    sb.append("    eeoCategory: ").append(toIndentedString(eeoCategory)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    compensation: ").append(toIndentedString(compensation)).append("\n");
    sb.append("    jobAd: ").append(toIndentedString(jobAd)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

