/*
 * Jobs API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.job.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * JobPosition
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-01T16:01:57.232855+01:00[Europe/Rome]")
public class JobPosition {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_POSITION_ID = "positionId";
  @SerializedName(SERIALIZED_NAME_POSITION_ID)
  private String positionId;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_INCUMBENT_NAME = "incumbentName";
  @SerializedName(SERIALIZED_NAME_INCUMBENT_NAME)
  private String incumbentName;

  public static final String SERIALIZED_NAME_POSITION_OPEN_DATE = "positionOpenDate";
  @SerializedName(SERIALIZED_NAME_POSITION_OPEN_DATE)
  private OffsetDateTime positionOpenDate;

  public static final String SERIALIZED_NAME_TARGET_START_DATE = "targetStartDate";
  @SerializedName(SERIALIZED_NAME_TARGET_START_DATE)
  private OffsetDateTime targetStartDate;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;


  public JobPosition id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")

  public String getId() {
    return id;
  }



  public void setId(String id) {
    this.id = id;
  }


  public JobPosition positionId(String positionId) {
    
    this.positionId = positionId;
    return this;
  }

   /**
   * Get positionId
   * @return positionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPositionId() {
    return positionId;
  }



  public void setPositionId(String positionId) {
    this.positionId = positionId;
  }


  public JobPosition type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getType() {
    return type;
  }



  public void setType(String type) {
    this.type = type;
  }


  public JobPosition incumbentName(String incumbentName) {
    
    this.incumbentName = incumbentName;
    return this;
  }

   /**
   * Get incumbentName
   * @return incumbentName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIncumbentName() {
    return incumbentName;
  }



  public void setIncumbentName(String incumbentName) {
    this.incumbentName = incumbentName;
  }


  public JobPosition positionOpenDate(OffsetDateTime positionOpenDate) {
    
    this.positionOpenDate = positionOpenDate;
    return this;
  }

   /**
   * Get positionOpenDate
   * @return positionOpenDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getPositionOpenDate() {
    return positionOpenDate;
  }



  public void setPositionOpenDate(OffsetDateTime positionOpenDate) {
    this.positionOpenDate = positionOpenDate;
  }


  public JobPosition targetStartDate(OffsetDateTime targetStartDate) {
    
    this.targetStartDate = targetStartDate;
    return this;
  }

   /**
   * Get targetStartDate
   * @return targetStartDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getTargetStartDate() {
    return targetStartDate;
  }



  public void setTargetStartDate(OffsetDateTime targetStartDate) {
    this.targetStartDate = targetStartDate;
  }


  public JobPosition status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStatus() {
    return status;
  }



  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobPosition jobPosition = (JobPosition) o;
    return Objects.equals(this.id, jobPosition.id) &&
        Objects.equals(this.positionId, jobPosition.positionId) &&
        Objects.equals(this.type, jobPosition.type) &&
        Objects.equals(this.incumbentName, jobPosition.incumbentName) &&
        Objects.equals(this.positionOpenDate, jobPosition.positionOpenDate) &&
        Objects.equals(this.targetStartDate, jobPosition.targetStartDate) &&
        Objects.equals(this.status, jobPosition.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, positionId, type, incumbentName, positionOpenDate, targetStartDate, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobPosition {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    positionId: ").append(toIndentedString(positionId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    incumbentName: ").append(toIndentedString(incumbentName)).append("\n");
    sb.append("    positionOpenDate: ").append(toIndentedString(positionOpenDate)).append("\n");
    sb.append("    targetStartDate: ").append(toIndentedString(targetStartDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

