/*
 * Jobs API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.job.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.smartrecruiters.api.job.model.Department;
import com.smartrecruiters.api.job.model.HiringTeamMemberResponseAllOfActions;
import com.smartrecruiters.api.job.model.Job;
import com.smartrecruiters.api.job.model.JobStatus;
import com.smartrecruiters.api.job.model.JobSummaryAllOf;
import com.smartrecruiters.api.job.model.Language;
import com.smartrecruiters.api.job.model.Location;
import com.smartrecruiters.api.job.model.PostingStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * JobSummary
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-01T16:01:57.232855+01:00[Europe/Rome]")
public class JobSummary {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_REF_NUMBER = "refNumber";
  @SerializedName(SERIALIZED_NAME_REF_NUMBER)
  private String refNumber;

  public static final String SERIALIZED_NAME_CREATED_ON = "createdOn";
  @SerializedName(SERIALIZED_NAME_CREATED_ON)
  private OffsetDateTime createdOn;

  public static final String SERIALIZED_NAME_UPDATED_ON = "updatedOn";
  @SerializedName(SERIALIZED_NAME_UPDATED_ON)
  private OffsetDateTime updatedOn;

  public static final String SERIALIZED_NAME_LAST_ACTIVITY_ON = "lastActivityOn";
  @SerializedName(SERIALIZED_NAME_LAST_ACTIVITY_ON)
  private OffsetDateTime lastActivityOn;

  public static final String SERIALIZED_NAME_DEPARTMENT = "department";
  @SerializedName(SERIALIZED_NAME_DEPARTMENT)
  private Department department;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private Location location;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private JobStatus status;

  public static final String SERIALIZED_NAME_POSTING_STATUS = "postingStatus";
  @SerializedName(SERIALIZED_NAME_POSTING_STATUS)
  private PostingStatus postingStatus;

  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  private Language language;

  public static final String SERIALIZED_NAME_ACTIONS = "actions";
  @SerializedName(SERIALIZED_NAME_ACTIONS)
  private HiringTeamMemberResponseAllOfActions actions;


  public JobSummary id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }



  public void setId(String id) {
    this.id = id;
  }


  public JobSummary title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTitle() {
    return title;
  }



  public void setTitle(String title) {
    this.title = title;
  }


  public JobSummary refNumber(String refNumber) {
    
    this.refNumber = refNumber;
    return this;
  }

   /**
   * Get refNumber
   * @return refNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRefNumber() {
    return refNumber;
  }



  public void setRefNumber(String refNumber) {
    this.refNumber = refNumber;
  }


  public JobSummary createdOn(OffsetDateTime createdOn) {
    
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }



  public void setCreatedOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
  }


  public JobSummary updatedOn(OffsetDateTime updatedOn) {
    
    this.updatedOn = updatedOn;
    return this;
  }

   /**
   * Job modification date
   * @return updatedOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Job modification date")

  public OffsetDateTime getUpdatedOn() {
    return updatedOn;
  }



  public void setUpdatedOn(OffsetDateTime updatedOn) {
    this.updatedOn = updatedOn;
  }


  public JobSummary lastActivityOn(OffsetDateTime lastActivityOn) {
    
    this.lastActivityOn = lastActivityOn;
    return this;
  }

   /**
   * Indicates last activity associated with a job
   * @return lastActivityOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates last activity associated with a job")

  public OffsetDateTime getLastActivityOn() {
    return lastActivityOn;
  }



  public void setLastActivityOn(OffsetDateTime lastActivityOn) {
    this.lastActivityOn = lastActivityOn;
  }


  public JobSummary department(Department department) {
    
    this.department = department;
    return this;
  }

   /**
   * Get department
   * @return department
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Department getDepartment() {
    return department;
  }



  public void setDepartment(Department department) {
    this.department = department;
  }


  public JobSummary location(Location location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Location getLocation() {
    return location;
  }



  public void setLocation(Location location) {
    this.location = location;
  }


  public JobSummary status(JobStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JobStatus getStatus() {
    return status;
  }



  public void setStatus(JobStatus status) {
    this.status = status;
  }


  public JobSummary postingStatus(PostingStatus postingStatus) {
    
    this.postingStatus = postingStatus;
    return this;
  }

   /**
   * Get postingStatus
   * @return postingStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PostingStatus getPostingStatus() {
    return postingStatus;
  }



  public void setPostingStatus(PostingStatus postingStatus) {
    this.postingStatus = postingStatus;
  }


  public JobSummary language(Language language) {
    
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Language getLanguage() {
    return language;
  }



  public void setLanguage(Language language) {
    this.language = language;
  }


  public JobSummary actions(HiringTeamMemberResponseAllOfActions actions) {
    
    this.actions = actions;
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HiringTeamMemberResponseAllOfActions getActions() {
    return actions;
  }



  public void setActions(HiringTeamMemberResponseAllOfActions actions) {
    this.actions = actions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobSummary jobSummary = (JobSummary) o;
    return Objects.equals(this.id, jobSummary.id) &&
        Objects.equals(this.title, jobSummary.title) &&
        Objects.equals(this.refNumber, jobSummary.refNumber) &&
        Objects.equals(this.createdOn, jobSummary.createdOn) &&
        Objects.equals(this.updatedOn, jobSummary.updatedOn) &&
        Objects.equals(this.lastActivityOn, jobSummary.lastActivityOn) &&
        Objects.equals(this.department, jobSummary.department) &&
        Objects.equals(this.location, jobSummary.location) &&
        Objects.equals(this.status, jobSummary.status) &&
        Objects.equals(this.postingStatus, jobSummary.postingStatus) &&
        Objects.equals(this.language, jobSummary.language) &&
        Objects.equals(this.actions, jobSummary.actions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, refNumber, createdOn, updatedOn, lastActivityOn, department, location, status, postingStatus, language, actions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobSummary {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    refNumber: ").append(toIndentedString(refNumber)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("    lastActivityOn: ").append(toIndentedString(lastActivityOn)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    postingStatus: ").append(toIndentedString(postingStatus)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

