/*
 * Jobs API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.job.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets PostingStatus
 */
@JsonAdapter(PostingStatus.Adapter.class)
public enum PostingStatus {
  
  PUBLIC("PUBLIC"),
  
  INTERNAL("INTERNAL"),
  
  NOT_PUBLISHED("NOT_PUBLISHED");

  private String value;

  PostingStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PostingStatus fromValue(String value) {
    for (PostingStatus b : PostingStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PostingStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final PostingStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PostingStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PostingStatus.fromValue(value);
    }
  }
}

