/*
 * Jobs API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.job.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ValidJobStatus
 */
@JsonAdapter(ValidJobStatus.Adapter.class)
public enum ValidJobStatus {
  
  CREATED("CREATED"),
  
  SOURCING("SOURCING"),
  
  FILLED("FILLED"),
  
  INTERVIEW("INTERVIEW"),
  
  OFFER("OFFER"),
  
  CANCELLED("CANCELLED");

  private String value;

  ValidJobStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ValidJobStatus fromValue(String value) {
    for (ValidJobStatus b : ValidJobStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ValidJobStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final ValidJobStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ValidJobStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ValidJobStatus.fromValue(value);
    }
  }
}

